import os
from playwright.sync_api import sync_playwright
OUT=os.path.join(os.environ.get("SHOT_DIR", "/home/claude"), "shots6"); os.makedirs(OUT, exist_ok=True)
U=os.environ.get("DEMO_URL", "file:///mnt/user-data/outputs/usc-ula-demo.html")
ok=[];bad=[]
def P(t): ok.append(t); print("PASS",t)
def F(t): bad.append(t); print("FAIL",t)
with sync_playwright() as p:
    b=p.chromium.launch()
    for label,(w,h),m in [("desktop",(1440,900),False),("phone",(390,844),True)]:
        c=b.new_context(viewport={'width':w,'height':h},is_mobile=m,has_touch=m)
        pg=c.new_page(); pg.on("pageerror", lambda e: F(f"JS ERROR {label}: {e}"))
        pg.goto(U); pg.wait_for_timeout(500)
        pg.locator('[data-start-fit]').click(); pg.wait_for_timeout(700)
        # q1, q2
        pg.locator('.option-card:has-text("Unwind")').first.click()
        pg.locator('[data-continue]:visible').first.click(); pg.wait_for_timeout(700)
        pg.locator('.option-card:has-text("Sauna & spa")').first.click()
        pg.locator('[data-continue]:visible').first.click(); pg.wait_for_timeout(800)
        # area question
        if "Where should we search" in pg.locator('#main h1').first.inner_text(): P(f"{label}: reached the area question")
        else: F(f"{label}: wrong screen: {pg.locator('#main h1').first.inner_text()}")
        if pg.locator('.geochip').is_visible(): P(f"{label}: detected-city chip shown: '{pg.locator('.geochip').inner_text().strip()}'")
        else: F(f"{label}: no detected-city chip")
        if pg.locator('.citypick').count()==0: P(f"{label}: picker closed by default")
        else: F(f"{label}: picker open by default")
        pg.screenshot(path=f"{OUT}/area-{label}.png")
        pg.locator('[data-change-city]').click(); pg.wait_for_timeout(300)
        n=pg.locator('[data-city]').count()
        P(f"{label}: Change opens {n} cities") if n==8 else F(f"{label}: expected 8 cities, got {n}")
        pg.locator('[data-city="Munich"]').click(); pg.wait_for_timeout(300)
        note=pg.locator('.citypick__note').inner_text()
        if "Berlin" in note and "Munich" in note: P(f"{label}: picking Munich is answered honestly")
        else: F(f"{label}: unclear note: {note[:120]}")
        pg.screenshot(path=f"{OUT}/citypick-{label}.png")
        # still exactly one CTA and the question still fits
        cta=pg.locator('[data-continue]:visible')
        P(f"{label}: still one Continue") if cta.count()==1 else F(f"{label}: {cta.count()} Continues")
        pg.locator('[data-city="Berlin"]').click(); pg.wait_for_timeout(300)
        if pg.locator('.citypick').count()==0: P(f"{label}: choosing Berlin closes the picker")
        else: F(f"{label}: picker stayed open after choosing Berlin")
        bb=cta.first.bounding_box()
        if bb['y']+bb['height']<=h: P(f"{label}: area question still fits ({int(bb['y']+bb['height'])} of {h})")
        else: F(f"{label}: area question now scrolls ({int(bb['y']+bb['height'])} of {h})")
        # the demand signal is in the journey data
        pg.locator('.option-card:has-text("Neuk")').first.click()
        pg.locator('[data-continue]:visible').first.click(); pg.wait_for_timeout(700)
        pg.locator('.option-card:has-text("Twice a week")').first.click()
        pg.locator('[data-continue]:visible').first.click(); pg.wait_for_timeout(900)
        pg.locator('[data-go="data"]').first.click(); pg.wait_for_timeout(600)
        txt=pg.locator('#main').inner_text()
        if "city_unavailable_requested" in txt: P(f"{label}: unmet city demand logged in journey data")
        else: F(f"{label}: city demand not in journey data")
        pg.screenshot(path=f"{OUT}/data-{label}.png", full_page=True)
        c.close()
    b.close()
print(f"\n=== {len(ok)} passed, {len(bad)} failed ===")
for x in bad: print("  !",x)
